id: P010311
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:43:27.698031
source_metadata:
  id: bdr:W1KG18275
  title: གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས་མུ་ཏིག་དོ་ཤལ།
  author: ''
  volumes:
    a0f3b1c85a3e4453b06ecb0e8c483dde:
      image_group_id: I1KG18304
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
